name: skin_lesion_det_env_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.13
  - pandas==1.2.4
  - numpy==1.22.3 
  - openpyxl==3.0.10
  - scikit-learn==1.0.2
  - scipy==1.7.3
  - scikit-image==0.16.2
  - opencv==4.6.0
  - matplotlib==3.4.3
  - pip==22.2.2
  - albumentations=1.3.0=pyhd8ed1ab_0
  - pip:
    - opencv-python-headless==4.10.0.84
    - torch==1.12.0
  