name: skin_class_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - conda=24.5.0
  - matplotlib
  - numpy=1.26.4
  - openpyxl
  - pandas
  - pip=24.0
  - python=3.11.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - scikit-image
  - scikit-learn
  - scipy
  - spyder
  - pip:
    - albumentations==1.4.11
    - annotated-types==0.7.0
    - eval-type-backport==0.2.0
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
   

